# Generated by Django 3.0.5 on 2020-04-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.IntegerField(default=0)),
                ('c2', models.IntegerField(default=0)),
                ('w1', models.FloatField(default=0)),
                ('w2', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('exid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
            ],
        ),
    ]
