# Generated by Django 3.0.5 on 2020-04-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20200428_1147'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='c1',
            field=models.IntegerField(default=0, verbose_name='Повторов левых'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='c2',
            field=models.IntegerField(default=0, verbose_name='Повторов правых'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='exid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='exercise.Exercise', verbose_name='Упражнения'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='w1',
            field=models.FloatField(default=0, verbose_name='Вес левый'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='w2',
            field=models.FloatField(default=0, verbose_name='Вес правый'),
        ),
    ]
